name: e2e

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  git-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        provider:
          - gitkit
          - gitlab-ce
          - gitlab
          - github
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Since this is a monorepo, changes in other packages will also trigger these e2e tests
      # meant only for the git package. This detects us whether the changed files are part of the
      # git directory. Subsequent steps check if this is true, before executing, thus helping us
      # run these tests only when there are changes to the git package.
      - name: Check for changes to git/ or e2e workflow
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            e2e:
              - '.github/workflows/e2e.yaml'
            git:
              - 'git/**'
      - name: Restore Go cache
        if: ${{ steps.filter.outputs.git == 'true' || steps.filter.outputs.e2e == 'true' || github.event_name == 'workflow_dispatch' }}
        uses: actions/cache@v3
        with:
          path: /home/runner/work/_temp/_github_home/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        if: ${{ steps.filter.outputs.git == 'true' || steps.filter.outputs.e2e == 'true' || github.event_name == 'workflow_dispatch' }}
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Run tests
        if: ${{ steps.filter.outputs.git == 'true' || steps.filter.outputs.e2e == 'true' || github.event_name == 'workflow_dispatch' }}
        run: |
          run_e2e=true

          # don't run e2e tests for PRs from forked repos for Github and Gitlab
          if [[ ${{ github.event_name }} != "pull_request" ]] || \
            [[ "${{ github.event.pull_request.head.repo.full_name }}" = ${{ github.repository }} ]]; then
            if [[ ${{ matrix.provider }} = "github" ]]; then
              export GO_TESTS="-run TestGitHubE2E"
              export GITHUB_TOKEN="${{ secrets.GITPROVIDER_BOT_TOKEN }}"
            elif [[ ${{ matrix.provider }} = "gitlab" ]]; then
              export GO_TESTS="-run TestGitLabE2E"
              export GITLAB_PAT="${{ secrets.GITLAB_BOT_TOKEN }}"
            fi
          else
              run_e2e=false
          fi

          if [[ ${{ matrix.provider }} = "gitkit" ]]; then
            export GO_TESTS="-run TestGitKitE2E"
            run_e2e=true
          elif [[ ${{ matrix.provider }} = "gitlab-ce" ]]; then
            export GO_TESTS="-run TestGitLabCEE2E"
            run_e2e=true
          fi

          if [ $run_e2e = true ]; then
            cd git/internal/e2e && GO_TESTS="${GO_TESTS}" ./run.sh
          else
            echo "skipping tests for ${{ matrix.provider }}"
          fi
