name: release-prep

on:
  push:
    branches:
      - main
      - 'flux/v2.*.x'

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: cmd/go.mod
          cache-dependency-path: "**/go.sum"
      - name: Run make prep
        run: make prep
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          commit-message: Prepare for release
          committer: GitHub <noreply@github.com>
          signoff: true
          branch: release-${{ github.ref_name }}
          title: Prepare for release
          body: |
            Automated release preparation for `${{ github.ref_name }}`.
