name: release-prep

on:
  push:
    branches:
      - main
      - 'flux/v2.*.x'

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: cmd/go.mod
          cache-dependency-path: "**/go.sum"
      - name: Run make prep-ci
        run: make prep-ci
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          commit-message: Prepare for release
          committer: GitHub <noreply@github.com>
          signoff: true
          branch: release-${{ github.ref_name }}
          title: Prepare for release
          body: |
            Automated release preparation for `${{ github.ref_name }}`.
